server:
  port: 8898

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/BC

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  main:
    allow-circular-references: true